server:
  port: 8000

spring:
  application:
    name: server0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/


logging:
  level:
    com.lc.template.server2: debug
