server:
  port: 7001

spring:
  application:
    name: server1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/


logging:
  level:
    com.lc.template.server1: debug
